// Generated by gencpp from file ros_projects/RectangleAreaRequest.msg
// DO NOT EDIT!


#ifndef ROS_PROJECTS_MESSAGE_RECTANGLEAREAREQUEST_H
#define ROS_PROJECTS_MESSAGE_RECTANGLEAREAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_projects
{
template <class ContainerAllocator>
struct RectangleAreaRequest_
{
  typedef RectangleAreaRequest_<ContainerAllocator> Type;

  RectangleAreaRequest_()
    : width(0.0)
    , height(0.0)  {
    }
  RectangleAreaRequest_(const ContainerAllocator& _alloc)
    : width(0.0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef float _width_type;
  _width_type width;

   typedef float _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::ros_projects::RectangleAreaRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_projects::RectangleAreaRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RectangleAreaRequest_

typedef ::ros_projects::RectangleAreaRequest_<std::allocator<void> > RectangleAreaRequest;

typedef boost::shared_ptr< ::ros_projects::RectangleAreaRequest > RectangleAreaRequestPtr;
typedef boost::shared_ptr< ::ros_projects::RectangleAreaRequest const> RectangleAreaRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_projects::RectangleAreaRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_projects::RectangleAreaRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_projects::RectangleAreaRequest_<ContainerAllocator1> & lhs, const ::ros_projects::RectangleAreaRequest_<ContainerAllocator2> & rhs)
{
  return lhs.width == rhs.width &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_projects::RectangleAreaRequest_<ContainerAllocator1> & lhs, const ::ros_projects::RectangleAreaRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_projects

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_projects::RectangleAreaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_projects::RectangleAreaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_projects::RectangleAreaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_projects::RectangleAreaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_projects::RectangleAreaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_projects::RectangleAreaRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_projects::RectangleAreaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed3043f094c99bdd8118bc5b0ddb14ba";
  }

  static const char* value(const ::ros_projects::RectangleAreaRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed3043f094c99bddULL;
  static const uint64_t static_value2 = 0x8118bc5b0ddb14baULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_projects::RectangleAreaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_projects/RectangleAreaRequest";
  }

  static const char* value(const ::ros_projects::RectangleAreaRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_projects::RectangleAreaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 width\n"
"float32 height\n"
;
  }

  static const char* value(const ::ros_projects::RectangleAreaRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_projects::RectangleAreaRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RectangleAreaRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_projects::RectangleAreaRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_projects::RectangleAreaRequest_<ContainerAllocator>& v)
  {
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_PROJECTS_MESSAGE_RECTANGLEAREAREQUEST_H
