// Generated by gencpp from file ros_projects/RectangleAreaResponse.msg
// DO NOT EDIT!


#ifndef ROS_PROJECTS_MESSAGE_RECTANGLEAREARESPONSE_H
#define ROS_PROJECTS_MESSAGE_RECTANGLEAREARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_projects
{
template <class ContainerAllocator>
struct RectangleAreaResponse_
{
  typedef RectangleAreaResponse_<ContainerAllocator> Type;

  RectangleAreaResponse_()
    : area(0.0)  {
    }
  RectangleAreaResponse_(const ContainerAllocator& _alloc)
    : area(0.0)  {
  (void)_alloc;
    }



   typedef float _area_type;
  _area_type area;





  typedef boost::shared_ptr< ::ros_projects::RectangleAreaResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_projects::RectangleAreaResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RectangleAreaResponse_

typedef ::ros_projects::RectangleAreaResponse_<std::allocator<void> > RectangleAreaResponse;

typedef boost::shared_ptr< ::ros_projects::RectangleAreaResponse > RectangleAreaResponsePtr;
typedef boost::shared_ptr< ::ros_projects::RectangleAreaResponse const> RectangleAreaResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_projects::RectangleAreaResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_projects::RectangleAreaResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_projects::RectangleAreaResponse_<ContainerAllocator1> & lhs, const ::ros_projects::RectangleAreaResponse_<ContainerAllocator2> & rhs)
{
  return lhs.area == rhs.area;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_projects::RectangleAreaResponse_<ContainerAllocator1> & lhs, const ::ros_projects::RectangleAreaResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_projects

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_projects::RectangleAreaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_projects::RectangleAreaResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_projects::RectangleAreaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_projects::RectangleAreaResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_projects::RectangleAreaResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_projects::RectangleAreaResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_projects::RectangleAreaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba46cd039de682077b3eaa09c3500c5c";
  }

  static const char* value(const ::ros_projects::RectangleAreaResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba46cd039de68207ULL;
  static const uint64_t static_value2 = 0x7b3eaa09c3500c5cULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_projects::RectangleAreaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_projects/RectangleAreaResponse";
  }

  static const char* value(const ::ros_projects::RectangleAreaResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_projects::RectangleAreaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 area\n"
"\n"
;
  }

  static const char* value(const ::ros_projects::RectangleAreaResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_projects::RectangleAreaResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.area);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RectangleAreaResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_projects::RectangleAreaResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_projects::RectangleAreaResponse_<ContainerAllocator>& v)
  {
    s << indent << "area: ";
    Printer<float>::stream(s, indent + "  ", v.area);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_PROJECTS_MESSAGE_RECTANGLEAREARESPONSE_H
